//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient_Info
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "First name is required")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last name is required")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Date of birth is required")]
        public System.DateTime DateOfBirth { get; set; }
        [StringLength(maximumLength: 16, MinimumLength = 16, ErrorMessage = "ID number must be 16 digits")]
        [Required(ErrorMessage = "ID Number is required")]
        public string IdNumber { get; set; }
        public string MedicalAid { get; set; }
    }
}
