//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Code_ProjectEntities2 : DbContext
    {
        public Code_ProjectEntities2()
            : base("name=Code_ProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Login>().ToTable("Login");
        }

        public virtual DbSet<Login> Login { get; set; }

        public virtual DbSet<Registration> Registrations { get; set; }
    }
}
